### ISSUE TITLE
Add ability to store arrays of data

### ISSUE THREAD

**Issue by howhelan** [pauwels-labs/redact-client#10]
Add the ability to store an array of data, which also brings up some other features we might want:
- Sorting and searching of arrays
    - Storing metadata fields which can be used for sorting or searching (eg. timestamps, tags).
- Pagination
- Aggregation of data
    - For example, "Tweeter" wants to retrieve all Posts from 2 users, and display them in chronological order.  But once it retrieves both user's posts, it has no way to rearrange them since it does not know what they are.  Can it instead make a request which will accomplish this?

**Comment by ajp-lqx** [comment]
I think we should split this ticket into two big tickets: searching/indexing, and aggregation. The former will involve coming up with a way to index encrypted data, either by leaking some indexable plain text, and the latter I think is fairly doable in the context of how data is stored currently if we add one additional field. Will try to add this feature in soon.
