### ISSUE TITLE
Host Relaying

### ISSUE THREAD

**Issue by howhelan** [pauwels-labs/redact-client#28]
When a user creates or edits a new piece of data, they need to be able to instruct the user's client to relay this information to the host.  This will allow the host to track references to data.

proposed solution:
Provide a "relay URL" to the client in the form of a query param or header.  When a POST request is submitted from within an iframe, the relay URL is passed again to the client, which creates or updates the data at the given path, and then sends a POST request to the relay URL with body
`{"reference": <Relay URL>, "userId": <User cert hash>}`

**Comment by ajpauwels** [comment]
done
